downloader:
  - acerbis
  - amersport
  - aps
  - aqua
  - asics
  - badboy
  - bde
  - bikeyoke
  - bronx
  - buff
  - bull
  - camel
  - cipher
  - click
  - cloumbia
  - craft
  - cygnet 
  - dkcompany
  - eafit
  - eldera
  - errea
  - esmsport
  - garmin
  - gore
  - graysinternational
  - grouperoyer 
  - hellyhansen
  - hummel
  - innov8pl
  - jako
  - jott 
  - kappa 
  - kswiss
  - leaderfit
  - lecoqsportif
  - macron
  - mizuno
  - newbalance 
  - newera
  - nike
  - nore
  - nowcompany
  - noreko
  - patrick
  - puma
  - rossignol
  - saeming 
  - salming 
  - salomon
  - saucony
  - selectmediabank
  - tremblay
  - trophygroup
  - wrangler